apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: mv5hxa2yl-python 
  janus-idp.io/tekton: mv5hxa2yl-python
  backstage.io/kubernetes-id: mv5hxa2yl-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: mv5hxa2yl-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml